import { mkdir } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import type { DevicePreset, Logger, RouteInfo } from "@storeshots/shared";
import { routeToFileName } from "@storeshots/shared";

export interface CaptureInput {
  root: string;
  outputDir: string;
  route: RouteInfo;
  device: DevicePreset;
  dryRun?: boolean;
  logger?: Logger;
}

export interface CaptureResult {
  route: RouteInfo;
  device: DevicePreset;
  rawPath: string;
  durationMs: number;
  skipped: boolean;
}

export interface ScreenshotEngine {
  capture(input: CaptureInput): Promise<CaptureResult>;
}

export function createScreenshotEngine(): ScreenshotEngine {
  return {
    async capture(input) {
      const startedAt = Date.now();
      const rawPath = path.join(input.outputDir, input.device.id, `${routeToFileName(input.route.path)}.png`);

      if (input.dryRun) {
        return {
          route: input.route,
          device: input.device,
          rawPath,
          durationMs: Date.now() - startedAt,
          skipped: true
        };
      }

      await mkdir(path.dirname(rawPath), { recursive: true });
      await renderFallbackCapture(input.route, input.device, rawPath);

      return {
        route: input.route,
        device: input.device,
        rawPath,
        durationMs: Date.now() - startedAt,
        skipped: false
      };
    }
  };
}

async function renderFallbackCapture(route: RouteInfo, device: DevicePreset, outputPath: string): Promise<void> {
  const title = escapeHtml(route.path === "/" ? "Home" : route.path);
  const subtitle = escapeHtml(device.name);
  const file = escapeHtml(path.basename(route.file));
  const width = device.width;
  const height = device.height;
  const safeTop = Math.round(height * 0.08);
  const cardWidth = Math.round(width * 0.82);
  const cardX = Math.round((width - cardWidth) / 2);
  const cardY = Math.round(height * 0.18);
  const cardHeight = Math.round(height * 0.34);

  const svg = `
  <svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="screen" x1="0" x2="1" y1="0" y2="1">
        <stop offset="0%" stop-color="#09090B"/>
        <stop offset="58%" stop-color="#111827"/>
        <stop offset="100%" stop-color="#020617"/>
      </linearGradient>
      <linearGradient id="accent" x1="0" x2="1">
        <stop offset="0%" stop-color="#3B82F6"/>
        <stop offset="100%" stop-color="#22C55E"/>
      </linearGradient>
    </defs>
    <rect width="${width}" height="${height}" fill="url(#screen)"/>
    <rect x="${cardX}" y="${cardY}" width="${cardWidth}" height="${cardHeight}" rx="44" fill="#111111" stroke="#27272A" stroke-width="3"/>
    <rect x="${cardX + 54}" y="${cardY + 58}" width="118" height="118" rx="30" fill="url(#accent)"/>
    <text x="${cardX + 54}" y="${cardY + 236}" font-family="Inter, Arial, sans-serif" font-size="64" font-weight="700" fill="#FAFAFA">${title}</text>
    <text x="${cardX + 54}" y="${cardY + 322}" font-family="Inter, Arial, sans-serif" font-size="36" fill="#A1A1AA">Captured for ${subtitle}</text>
    <text x="${cardX + 54}" y="${cardY + 386}" font-family="JetBrains Mono, Menlo, monospace" font-size="28" fill="#22C55E">source: ${file}</text>
    <rect x="${cardX}" y="${cardY + cardHeight + 80}" width="${cardWidth}" height="26" rx="13" fill="#27272A"/>
    <rect x="${cardX}" y="${cardY + cardHeight + 80}" width="${Math.round(cardWidth * 0.68)}" height="26" rx="13" fill="#3B82F6"/>
    <text x="${cardX}" y="${height - safeTop}" font-family="JetBrains Mono, Menlo, monospace" font-size="30" fill="#A1A1AA">Generated by Storeshots</text>
  </svg>`;

  await sharp(Buffer.from(svg)).png().toFile(outputPath);
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;");
}
